"""empty message

Revision ID: 096a1eda5434
Revises: 79e74d3fbe66
Create Date: 2019-06-18 14:24:11.687663

"""

# revision identifiers, used by Alembic.
revision = '096a1eda5434'
down_revision = '79e74d3fbe66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
