"""empty message

Revision ID: 0c495cb20a08
Revises: 5d1bcf623a67
Create Date: 2019-06-20 09:42:49.978782

"""

# revision identifiers, used by Alembic.
revision = '0c495cb20a08'
down_revision = '5d1bcf623a67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
