"""empty message

Revision ID: 0cf91b3f4ded
Revises: 8e3a0cddb277
Create Date: 2019-06-21 08:17:11.997461

"""

# revision identifiers, used by Alembic.
revision = '0cf91b3f4ded'
down_revision = '8e3a0cddb277'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
