"""empty message

Revision ID: 20faa390912b
Revises: 0cf91b3f4ded
Create Date: 2019-06-21 09:13:30.943696

"""

# revision identifiers, used by Alembic.
revision = '20faa390912b'
down_revision = '0cf91b3f4ded'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
