"""empty message

Revision ID: 497c73d0a274
Revises: f13448841e74
Create Date: 2019-06-18 13:15:38.744953

"""

# revision identifiers, used by Alembic.
revision = '497c73d0a274'
down_revision = 'f13448841e74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
