"""empty message

Revision ID: 4fd2d6de2a71
Revises: 6dcf0fa2b6f3
Create Date: 2019-06-20 07:34:34.134064

"""

# revision identifiers, used by Alembic.
revision = '4fd2d6de2a71'
down_revision = '6dcf0fa2b6f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
