"""empty message

Revision ID: 5d1bcf623a67
Revises: 4fd2d6de2a71
Create Date: 2019-06-20 08:34:04.029097

"""

# revision identifiers, used by Alembic.
revision = '5d1bcf623a67'
down_revision = '4fd2d6de2a71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark',
    sa.Column('movie', sa.String(length=300), nullable=False),
    sa.Column('user_first_name', sa.String(length=300), nullable=False),
    sa.Column('user_last_name', sa.String(length=300), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('movie', 'user_first_name', 'user_last_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark')
    # ### end Alembic commands ###
