"""empty message

Revision ID: 6dcf0fa2b6f3
Revises: 096a1eda5434
Create Date: 2019-06-19 08:28:08.982652

"""

# revision identifiers, used by Alembic.
revision = '6dcf0fa2b6f3'
down_revision = '096a1eda5434'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
