"""empty message

Revision ID: 6e21cdbbff5b
Revises: 497c73d0a274
Create Date: 2019-06-18 13:16:58.174208

"""

# revision identifiers, used by Alembic.
revision = '6e21cdbbff5b'
down_revision = '497c73d0a274'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
