"""empty message

Revision ID: 73dd36df7df4
Revises: 6e21cdbbff5b
Create Date: 2019-06-18 13:58:05.536769

"""

# revision identifiers, used by Alembic.
revision = '73dd36df7df4'
down_revision = '6e21cdbbff5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
