"""empty message

Revision ID: 79e74d3fbe66
Revises: 73dd36df7df4
Create Date: 2019-06-18 14:03:18.881040

"""

# revision identifiers, used by Alembic.
revision = '79e74d3fbe66'
down_revision = '73dd36df7df4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
