"""empty message

Revision ID: 82e8b4714628
Revises: b9f1fe34e650
Create Date: 2019-06-20 14:25:34.577827

"""

# revision identifiers, used by Alembic.
revision = '82e8b4714628'
down_revision = 'b9f1fe34e650'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
