"""empty message

Revision ID: 8e3a0cddb277
Revises: ff29551e8db1
Create Date: 2019-06-21 07:31:33.560266

"""

# revision identifiers, used by Alembic.
revision = '8e3a0cddb277'
down_revision = 'ff29551e8db1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
