"""empty message

Revision ID: b9f1fe34e650
Revises: 0c495cb20a08
Create Date: 2019-06-20 13:54:37.563443

"""

# revision identifiers, used by Alembic.
revision = 'b9f1fe34e650'
down_revision = '0c495cb20a08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
