"""empty message

Revision ID: c3111afe8984
Revises: 51e2c29ad95
Create Date: 2019-06-18 12:18:32.797938

"""

# revision identifiers, used by Alembic.
revision = 'c3111afe8984'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('producer', sa.String(length=300), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
