"""empty message

Revision ID: f13448841e74
Revises: c3111afe8984
Create Date: 2019-06-18 12:42:17.706312

"""

# revision identifiers, used by Alembic.
revision = 'f13448841e74'
down_revision = 'c3111afe8984'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
