"""empty message

Revision ID: ff29551e8db1
Revises: 82e8b4714628
Create Date: 2019-06-20 15:55:17.159095

"""

# revision identifiers, used by Alembic.
revision = 'ff29551e8db1'
down_revision = '82e8b4714628'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
